### ISSUE TITLE
Tutorial issue

### ISSUE THREAD

**Issue by andzdroid** [iacobson/ecspanse#1]
Something is wrong with the MoveHero system:

```elixir
  @impl Ecspanse
  def setup(data) do
    data
    |> Ecspanse.add_startup_system(Systems.SpawnHero)
    |> Ecspanse.add_system(Systems.RestoreEnergy, run_if: [{__MODULE__, :energy_not_max}])
    |> Ecspanse.add_system(Systems.MoveHero, after: [Systems.RestoreEnergy])
    |> Ecspanse.add_frame_end_system(Ecspanse.System.Timer)
  end
```

I run `Demo.API.move_hero(:up)` many times but the hero only moves once or a few times.

This happens even when I clone the tutorial repo and run that.

**Comment by iacobson** [comment]
First of all thanks for trying the library and thanks for reaching out.

This shouldn't be the case. The 'run_after' option does not depend on the before event being executed or not. This option is evaluated only once, at server start-up, when the async systems are grouped into batches. Then the scheduler tries to execute every system in every batch. 

In our case, the "move" was batched after the "energy restore", but it should run every time a move event is scheduled, independent of the "restore energy" system.

Of course, if your energy reaches zero, then you will be able to move only once every 3 seconds, when you get back one energy. But that is game mechanics, not library. Can you check if that was your case? I'm pretty sure when playing the demo in Livebook I could move on any keystroke, as long as I had energy.

That being said, I agree that the subject is not clear in the docs and in the tutorial. So as soon as I will come back from the holidays, I will make it more clear how the system ordering works. I could also write a test for your case in the 'ecspanse_demo' repo

**Comment by andzdroid** [comment]
Sorry, I misdiagnosed the issue. I updated the issue description without trying to diagnose it.

Basically I run the move command multiple times but the hero only moves once, even though there is plenty of energy left. I can reproduce this on the tutorial repo without any changes.

However I am on elixir 1.14 instead of 1.15. Could that be the reason for this behaviour?

**Comment by iacobson** [comment]
I would find it very strange if the Elixir version would be the issue.

How do you test? Is it in the iex console by running the provided API functions manually?

If so, could you paste here the sequence of functions you run, together with their return?

Basically copy-paste from your iex?

**Comment by andzdroid** [comment]
This is from cloning the tutorial repo with no changes:

```
PS ecspanse_demo> iex.bat -S mix                              
Interactive Elixir (1.14.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Demo.API.fetch_hero_details
%{
  energy: 53,
  inventory: [%{name: "Potion"}, %{name: "Potion"}, %{name: "Boots"}],
  max_energy: 100,
  name: "Hero",
  pos_x: 0,
  pos_y: 0,
  resources: [%{amount: 0, name: "Gems"}, %{amount: 0, name: "Gold"}] 
}
iex(2)> Demo.API.move_hero(:up)
:ok     
iex(3)> Demo.API.fetch_hero_details
%{
  energy: 56,
  inventory: [%{name: "Potion"}, %{name: "Potion"}, %{name: "Boots"}],
  max_energy: 100,
  name: "Hero",
  pos_x: 0,
  pos_y: 0,
  resources: [%{amount: 0, name: "Gems"}, %{amount: 0, name: "Gold"}] 
}
iex(4)> Demo.API.move_hero(:up)     
:ok     
iex(5)> Demo.API.move_hero(:up)
:ok     
iex(6)> Demo.API.move_hero(:up)
:ok     
iex(7)> Demo.API.fetch_hero_details
%{
  energy: 58,
  inventory: [%{name: "Potion"}, %{name: "Potion"}, %{name: "Boots"}],
  max_energy: 100,
  name: "Hero",
  pos_x: 0,
  pos_y: 0,
  resources: [%{amount: 0, name: "Gems"}, %{amount: 0, name: "Gold"}] 
}
iex(8)> Demo.API.move_hero(:up)     
:ok     
iex(9)> Demo.API.move_hero(:up)
:ok
iex(10)> Demo.API.move_hero(:up)
:ok
iex(11)> Demo.API.move_hero(:up)
:ok
iex(12)> Demo.API.move_hero(:up)
:ok
iex(13)> Demo.API.fetch_hero_details
%{
  energy: 58,
  inventory: [%{name: "Potion"}, %{name: "Potion"}, %{name: "Boots"}],
  max_energy: 100,
  name: "Hero",
  pos_x: 0,
  pos_y: 1,
  resources: [%{amount: 0, name: "Gems"}, %{amount: 0, name: "Gold"}]
}
```

**Comment by iacobson** [comment]
Thank you. It will require indeed some investigation on my side. I will check Tuesday and get back to you.

**Comment by iacobson** [comment]
For the upcoming investigation, would you pls tell me your Erlang version you use together with Elixir 1.14.5? Just in case that would be needed to try to reproduce.

**Comment by andzdroid** [comment]
Sure, I'm on 25.3.2.5

**Comment by iacobson** [comment]
I can now consistently reproduce the issue with a test. I think the problem is a race condition when a new event is scheduled in the interval between the events are prepared for the current frame, and when they are deleted from the ETS table.

I'm working on a fix and hope to publish a new version in the following days.

**Comment by iacobson** [comment]
[Version 0.3.1](https://hexdocs.pm/ecspanse/changelog.html) addressing the bug you signaled is now released.
I updated also the Demo project used for the tutorial to v0.3.1. So you can pull and test again if you want.

Thank you again for pointing this bug and for providing all the details.

**Comment by andzdroid** [comment]
Great, thanks! Looking forward to trying this out again
