### ISSUE TITLE
Missing parts in the tutorial

### ISSUE THREAD

**Issue by hl** [iacobson/ecspanse#22]
I believe some parts are missing in the tutorial. The demo repo provides some missing insight and I will keep updating this as I follow the tutorial:

The `Ecspanse.Entity` is missing in the tutorial from:
https://github.com/iacobson/ecspanse_demo/blob/ad29dc421b08435ff83fc81d82508e1a0f44c750/lib/demo/api.ex#L9

and is needed here: https://github.com/iacobson/ecspanse_demo/blob/ad29dc421b08435ff83fc81d82508e1a0f44c750/lib/demo/api.ex#L20

The function `list_hero_resources/1` is in the tutorial but adding it to the `fetch_hero_details/0` function under the `resources` key part is missing.

**Comment by hl** [comment]
The same applies for the function `list_hero_inventory/1`, the function is in the tutorial, not an example of hooking it up in the `fetch_hero_details/0`.

**Comment by iacobson** [comment]
Thank you! I will update the docs and include them in the next release `0.8.1`
